# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOROOT: '/usr/local/go1.13' # Go installation path

steps:
- script: |
    ln -sf /usr/local/go1.13/bin/* /usr/bin/
  displayName: 'Set up workspace'
  
- script: |
    go1.13 version
    go1.13 get -v -t -d  ./...
  displayName: 'Install dependencies'

- script: |
    go1.13 version
    go1.13 test -v ./...
  displayName: 'Run test suite'

- script: |
    go1.13 version
    go1.13 build -v .
  displayName: 'Build'
