# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOROOT: '/usr/local/go1.13' # Go installation path

steps:
- script: |
    go version
    go get -v -t -d  ./...
  displayName: 'Install dependencies'

- script: |
    go version
    go test -v ./...
  displayName: 'Run test suite'

- script: |
    go version
    go build -v .
  displayName: 'Build'
